name: Build DCS KMC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PATH: /usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake build-essential libgcrypt20-dev maven swig \
            libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat python3-pip curl

      - name: Download JUnit 4.13.2 jar
        run: |
          mkdir -p kmc_sdls/kmc_sdls_java/kmc_sdls_java_test
          curl -L -o kmc_sdls/kmc_sdls_java/kmc_sdls_java_test/junit-4.13.2.jar \
            https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar

      - name: Install Python modules
        run: |
          pip3 install --upgrade pip
          pip3 install cffi==1.14.5 invoke==2.2.0 pycryptodome==3.20.0

      - name: Make build script executable
        run: chmod +x ./kmc-resources/scripts/build.sh

      - name: Run build script with skip-test
        run: ./kmc-resources/scripts/build.sh skip-test
        env:
          CMAKE_INCLUDE_PATH: /usr/include/mariadb
          CFLAGS: -Wno-address

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dcs-kmc-build
          path: |
            ./kmc/**/target/*.jar
            ./crypto-lib/build/lib
