name: Build and Export KMC

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PREFIX: /usr/local/kmc
      BINPATH: /usr/local/kmc/bin
      LIBPATH: /usr/local/kmc/lib
      CFGPATH: /usr/local/kmc/etc
      LOGPATH: /var/log/kmc
      CRYPTOSVC_PREFIX: /usr/local/cryptosvc
      CRYTPOSVC_LIBPATH: /usr/local/cryptosvc/lib
      CRYPTOSVC_CFGPATH: /usr/local/cryptosvc/etc
      CRYPTOSVC_LOGPATH: /var/log/cryptosvc
      SDLSSVC_PREFIX: /usr/local/sdls
      SDLSSVC_LIBPATH: /usr/local/sdls/lib
      SDLSSVC_CFGPATH: /usr/local/sdls/etc
      SDLSSVC_LOGPATH: /var/log/sdls
      SAMGMTSVC_PREFIX: /usr/local/samgmt
      SAMGMTSVC_LIBPATH: /usr/local/samgmt/lib
      SAMGMTSVC_CFGPATH: /usr/local/samgmt/etc
      SAMGMTSVC_LOGPATH: /var/log/samgmt
      VERSION: 1.0.0
      SRC_CRYPTO_LIB: ./crypto-lib
      SRC_KMC: ./kmc
      SRC_KMIP: ./kmip

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgcrypt20-dev maven swig libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat

      - name: Set permissions for build script
        run: chmod +x ./kmc-resources/scripts/build.sh

      - name: Run build script
        run: ./kmc-resources/scripts/build.sh skip-test
        env:
          CMAKE_INCLUDE_PATH: /usr/include/mariadb
          CFLAGS: -Wno-address

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kmc-build
          path: |
            ./kmc/**/target/*.jar
            ./crypto-lib/build/lib
