# .github/workflows/hadolint.yml
name: Hadolint (Manual)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  hadolint:
    name: Lint all Dockerfiles
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          wget -qO /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Find and lint all Dockerfiles
        run: |
          echo "Scanning all Dockerfiles..."
          find . -type f -iname 'Dockerfile*' -print0 | xargs -0 -n1 hadolint --failure-threshold error
