name: Generate SBOM (SPDX)

on:
  workflow_run:
    workflows: ["Build DCS KMC"] 
    types:
      - completed

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dcs-kmc-build
          path: ./build-output

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.15.2

      - name: Generate SPDX SBOM
        run: |
          ./syft dir:./build-output -o spdx-json > sbom.spdx.json

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json
